### ISSUE TITLE
Model Browser Weirdness

### ISSUE THREAD

**Issue by Gocnak** [SCell555/sdk-2013-hammer#3]
Model browser crashes on Release binaries, but opens (and does not display the model) on Debug builds.

You can recreate this crash by making any prop_dynamic, and trying to select the model for it. Odd stuff. Not sure what causes it, making this here since it's one of the last few parity bugs I've seen.

Seems like CMDLPanel is an engine panel. I know TF2 uses a different approach to displaying a model as well, with rendering it directly or something.

**Comment by SCell555** [comment]
CMDLPicker from matsys_controls.lib was crashing when creating new instance, my guess is that it's because of layout changes in vgui::Panel, so I copied entire implementation to ModelBrowser.cpp and gave all panels suffix 2. I think CMDLPanel is suffering from the same issue, and same might be for all classes from matsys_controls.lib.

Also any more complex model will cause studio renderer to return [null transformation matrix](https://github.com/SCell555/sdk-2013-hammer/blob/master/hammer/StudioModel.cpp#L511) and all models will not render until you move your mouse to other view.

**Comment by SCell555** [comment]
Oh wow, that issue was deeper than I had initially anticipated. I had few problems with datamodel when I was moving the source to 2013, originally CHammer class was derived from CTier3DmAppSystem and experienced the same problem of missing symbols.
But since you managed to fix this issue in your fork, I will close this issue.
